# This is the path where your dotfiles will live
manifest_path=~/.dotfiles
# Theme for output colors
theme=dracula
# Whether to backup dotfiles with git
use_git=True
# Whether to backup dotfiles to a remote source when using git.
use_remote=False
# The remote platform to use for backups
remote_platform=github
# URL for the remote repo
remote_url=
# Auth method to use for the remote git operations
# gh_cli | ssh | pat
remote_auth_method=
